name: 'solace-poc'

services:
  rabbit:
    hostname: 'rabbitmq'
    image: rabbitmq:3-management
    environment:
        - RABBITMQ_LOG_BASE=/var/log/rabbitmq
    ports:
        - "15672:15672"
        - "15692:15692"
        - "5672:5672"
        - "5671:5671"
    volumes:
        - rabbitmq-storage:/var/lib/rabbitmq
        - ./docker/rabbitmq-ssl/enabled_plugins:/etc/rabbitmq/enabled_plugins

  solace:
    container_name: pubSubStandardSingleNode
    image: solace/solace-pubsub-standard:latest
    volumes:
      - "storage-group:/var/lib/solace"
    shm_size: 1g
    ulimits:
      core: -1
      nofile:
        soft: 2448
        hard: 6592
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 1
    ports:
    #Port Mappings:  With the exception of SMF, ports are mapped straight
    #through from host to container.  This may result in port collisions on
    #commonly used ports that will cause failure of the container to start.
      #Web transport
      - '8008:8008'
      #Web transport over TLS
      - '1443:1443'
      #SEMP over TLS
      - '1943:1943'
      #MQTT Default VPN
      - '1883:1883'
      #AMQP Default VPN over TLS
      - '5673:5671'
      #AMQP Default VPN
      - '5674:5672'
      #MQTT Default VPN over WebSockets
      - '8000:8000'
      #MQTT Default VPN over WebSockets / TLS
      - '8443:8443'
      #MQTT Default VPN over TLS
      - '8883:8883'
      #SEMP / PubSub+ Manager
      - '8080:8080'
      #REST Default VPN
      - '9000:9000'
      #REST Default VPN over TLS
      - '9443:9443'
      #SMF
      - '55554:55555'
      #SMF Compressed
      - '55003:55003'
      #SMF over TLS
      - '55443:55443'
      #SSH connection to CLI
      - '2222:2222'
    environment:
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin
      - system_scaling_maxconnectioncount=100

volumes:
  rabbitmq-storage:
  storage-group:
